pipeline {
    agent any

    environment {
        // Define any environment variables needed
        DOTNET_SDK_VERSION = '3.1'
        IMAGE_TAG = 'muhohoweb:3.0.0'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout from source control
                git url: 'https://github.com/samkirigha/staging.git', branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Build the Image"

                    // sh '''
                    //     /opt/homebrew/bin/docker build -t muhohoweb/ticketsservice:1.0.5  ticketsservice
                    // '''
                    // Login to Docker registry if necessary
                    //--platform linux/
                    //--platform linux/arm64
                    // sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
                    // Build and push Docker image
                    // docker.build(IMAGE_TAG, './publish').push()
                }
            }
        }

        stage('Deploy Config maps') {
            steps {
                script {
                    sh '''
                        kubectl apply -f kubernetes/db-configs.yml
                    '''
                }
            }
        }

        stage('Push to Docker hub') {
            steps {
                script {
                    echo "Pushing to Docker hub"

                    // sh '''
                    //     /opt/homebrew/bin/docker push muhohoweb/ticketsservice:1.0.5
                    // '''
                    // Login to Docker registry if necessary
                    //--platform linux/
                    //--platform linux/arm64
                    // sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
                    // Build and push Docker image
                    // docker.build(IMAGE_TAG, './publish').push()
                }
            }
        }
    
    }
}

